backend:
  name: github
  repo: RuvikGroup/content
  branch: main
  base_url: https://cms-auth.ruvikgroup.com

media_folder: apps/asiaflare-blog/public/images
public_folder: /images

collections:
  - name: asiaflare-blog
    label: AsiaFlare Blog Posts
    folder: apps/asiaflare-blog/src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime }
      - { label: Author, name: author, widget: string, default: "AsiaFlare Team" }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Body, name: body, widget: markdown }

  - name: latinflare-blog
    label: LatinFlare Blog Posts
    folder: apps/latinflare-blog/src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDate, widget: datetime }
      - { label: Author, name: author, widget: string, default: "LatinFlare Team" }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Body, name: body, widget: markdown }
